spring:
  h2:
    console:
      enabled: 'true'
      path: /h2
  datasource:
    url: 'jdbc:h2:mem:testdb'
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
logging:
  file:
    path: /home/logs
server:
  port: '8090'
